version: 2

models:
  - name: int_sales_by_category
    description: "This model aggregates sales data by product category."
    columns:
      - name: product_category_name
        description: "The category to which the product belongs."
        tests:
          - not_null
      - name: total_sales
        description: "The total sales amount for the product category."
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_category_name

  - name: int_avg_delivery_time
    description: "This model calculates the average delivery time for each order."
    columns:
      - name: order_id
        description: "Unique identifier for each order."
        tests:
          - unique
          - not_null
      - name: avg_delivery_time
        description: "The average time taken for delivery in days."
        tests:
          - not_null

  - name: int_orders_by_state
    description: "This model counts the number of orders by state."
    columns:
      - name: state
        description: "The state where the order was delivered."
        tests:
          - not_null
      - name: total_orders
        description: "The total number of orders delivered in the state."
        tests:
          - not_null
